# Generated by Django 2.0.7 on 2018-07-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(max_length=20)),
                ('gDate', models.DateTimeField()),
                ('gTotalNum', models.IntegerField()),
                ('gGirlNum', models.IntegerField()),
                ('gBoyNum', models.IntegerField()),
                ('gIsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sGender', models.BooleanField()),
                ('sAge', models.IntegerField()),
                ('sContend', models.CharField(max_length=20)),
                ('sIsDelete', models.BooleanField(default=False)),
                ('sGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades')),
            ],
        ),
    ]
